Askdjango/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns =+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

blog/urls.py
from django.urls import path

app_name = 'blog'

urlpatterns = [
]

shop/urls.py
from django.urls import path
from . import views
from .converters import FourDigitYearConverter
from django.urls import register_converter

register_converter(FourDigitYearConverter, 'yyyy')

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('archives/<yyyy:year>/', views.archives_year),
    path('<int:item_id>/', views.detail, name='detail'),
    path('new/', views.item_new, name='item_new'),
    path('<int:pk>/edit/', views.item_edit, name='item_edit'),

]

blog/models.py
from django.conf import settings
from django.db import models
from Askdjango.utils import uuid_upload_to


class Post(models.Model):
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    tag_set = models.ManyToManyField('Tag', blank=True)
    content = models.TextField()
    photo = models.ImageField(blank=True, upload_to=uuid_upload_to)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

common/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.conf import settings
from django.db import models

from Askdjango.utils import uuid_upload_to


class Item(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField(blank=True)
    photo = models.ImageField(blank=True, upload_to=uuid_upload_to)
    price = models.PositiveIntegerField()
    is_publish = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'<{self.pk}> {self.name}'

# class Post(models.Model):
#     author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
# blog의 related_name 충돌이 일어남

shop/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

common/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView
from . models import Item
from .forms import ItemForm

def archives_year(request, year):
    return HttpResponse(f'{year}년도에 대한 정보')


def index(request):
    item_list = Item.objects.order_by('-created_at')
    content = {'item_list':item_list}
    return render(request, 'shop/item_lsit.html', content)

def detail(request, item_id):
    question = get_object_or_404(Item, id=item_id)
    content = {'question': question}
    return render(request, 'shop/detail.html', content)


# def item_new(request, item=None):
#     if request.method == 'POST':
#         form = ItemForm(request.POST, request.FILES, instance=item)
#         if form.is_valid():
#             item = form.save()
#             return redirect(item)
#     else:
#         form = ItemForm(instance=item)

#     return render(request, 'shop/item_form.html', {
#         'form': form,
#     })


# def item_edit(request, pk):
#     item = get_object_or_404(Item, pk=pk)
#     return item_new(request, item)

item_new = CreateView.as_view(model=Item, form_class=ItemForm)

item_edit = UpdateView.as_view(model=Item, form_class=ItemForm)

Askdjango/templates/layout.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Ask Django{% endblock %}</title>
    {% block extra_head %}
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}

    {% block extra_body %}
        <script src="{% static 'main.js' %}"></script>
    {% endblock %}

</body>
</html>

blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

shop/templates/layout.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Ask Django{% endblock %}</title>
    {% block extra_head %}
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}

    {% block extra_body %}
        <script src="{% static 'main.js' %}"></script>
    {% endblock %}

</body>
</html>

shop/templates/shop/detail.html
{% extends 'layout.html' %}
{% load humanize %}
{% block content %}
    <h2>{{ itme.name }}</h2>
    {% if item.photo %}
        {{ item.photo.url }}<br/>
        {{ item.photo.path }}<br/>
    {% endif %}
    가격:{{ item.price|intcomma }}원
    {% if item.desc %}
        {{ item.desc }}
    {% endif %}
{% endblock %}

shop/templates/shop/item_form.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    </head>
    <body>
        <div class="container">
            <div class="col-sm-12">
                <h2>New Item</h2>

                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
                    <table class="table table-bordered">
                        {{ form.as_table }}
                    </table>
                    <input type="submit" value="저장하기" class="btn btn-primary" />
                </form>
            </div>
        </div>
    </body>
</html>

shop/templates/shop/item_lsit.html
{% extends 'layout.html' %}
{% block content %}
    {% if item_list %}
        {% for item in item_list %}
        {{ forloop.counter }}
        <p><a href="{% url 'shop:index' %}">{{ item.name }}</a></p>
        {% endfor %}

    {% else %}
        <p>등록된 상품이 없습니다.</p>
    {% endif %}
{% endblock %}